### ISSUE TITLE
How to get the LLVM IR with your library exactly? the .bc  file? Is that a real LLVM IR that I can use llvm utils like llvm-dis on that? If yes, does it produce debug info?

### ISSUE THREAD

**Issue by dmikushin** [apc-llc/nvcc-llvm-ir#2]
The tool is a hack around NVIDIA CUDA compiler by means of dynamic code injection. It makes LLVM IR Module pointer available to the injector function. The Module could be further dumped by its pointer either in binary or text format, or modified on the fly.

I suppose, debug info should be inlined in LLVM IR in form of metadata nodes. At least, this is how it was done by the mainline LLVM at that time.

**Comment by hzhang86** [comment]
So...I need to write the dump function by myself given the module pointer? How do I dump it to the regular LLVM IR bitcode format?

Thanks

**Comment by dmikushin** [comment]
It's all shown here:
https://github.com/apc-llc/nvcc-llvm-ir#unoptimized-llvm-ir-retrieval

In order to get the module pointer, you need to wrap around the libNVVM
function called inside the CUDA compiler.


2017-09-06 6:49 GMT+03:00 hzhang86 <notifications@github.com>:

**Comment by hzhang86** [comment]
The same code is in cicc.cpp, so all I need to do is to uncomment the "outs()<<"  line in modifyModule function? 
How to "wrap around the libNVVM function called inside the CUDA compiler" ? sorry I'm totally new to CUDA

Thanks

**Comment by dmikushin** [comment]
Yes you can uncomment this line in cicc.cpp to see the textual IR code of
your CUDA source.

The concept of wrapping has nothing to do with CUDA. It's a standard
library trick. Almost every app uses system libraries, right? Those
libraries provide C/C++ runtime functions - printf, memory allocation, etc
etc. If the app links to the library dynamically (such library is called
shared), the app and the library are independent runtime components. This
yields that you can substitute the original shared library libfoo1.so used
by app with your own libfoo2.so and implement there functions with the same
signature as in the original libfoo1.so. From the app's point of view, the
change will be unnoticed. More specifically, if an app uses malloc()
function, you can implement your own malloc() in the separate shared
library and load it before the standard one (called library preloading).
Then, inside you own malloc() you can do whatever you need, besides calling
the original system malloc() function. This is called wrapping malloc()
function call.

2017-09-06 16:28 GMT+03:00 hzhang86 <notifications@github.com>:
