### ISSUE TITLE
Can I use this to get debug info compiled by llvm?

### ISSUE THREAD

**Issue by Char-Aznable** [apc-llc/nvcc-llvm-ir#4]
This was asked before http://lists.llvm.org/pipermail/llvm-dev/2017-June/114094.html
Does this repo provide tool to do similar thing?

**Comment by dmikushin** [comment]
My tool intends to modify LLVM IR generated by NVIDIA CUDA compiler. Note NVIDIA CUDA compiler has its own specific flag "-G" to add debug information in GPU code. Moreover, to eliminate a possible confusion: NVIDIA CUDA frontend is *not* clang. However, it is true that you can use the tool to manipulate debug info generated by NVIDIA CUDA frontend.
