### ISSUE TITLE
Using LLVM14 to run the code but seeing the undefined symbol error

### ISSUE THREAD

**Issue by Luke20000429** [apc-llc/nvcc-llvm-ir#5]
I changed some in cicc.cpp to make it compilable but run `make test` returns me an error.
```
CICC_MODIFY_UNOPT_MODULE=1 LD_PRELOAD=./libnvcc.so nvcc -arch=sm_61 test2.cu -rdc=true -c -keep
cicc: symbol lookup error: ./libcicc.so: undefined symbol: _ZN4llvm5dwarf23AttributeEncodingStringEj
ptxas fatal   : Input file 'test2.ptx' could not be opened
ptxas fatal   : Ptx assembly aborted due to errors
make: *** [makefile:27: test2_unopt] Error 255
```
I've checked with `nm -D` that symbol exists but undefined `U _ZN4llvm5dwarf23AttributeEncodingStringEj`.
I wonder where it is used, any essential llvm headers are missing?

**Comment by Luke20000429** [comment]
I also tried with LLVM-6.0 and it returns the same error

**Comment by dmikushin** [comment]
Hi @Luke20000429 , I assume you have made changes to the `Makefile`, but I could not see them anywhere. So here is a guess: in the `Makefile` you are replacing a set of libraries with just `-lLLVM-14`. This is not the same: the original set of libraries were static libraries, while `-lLLVM-14` is a *shared* library. Please keep the original set of linked libraries (or fix it accordingly), and you will not have missing symbols.
